
const ListOfParticipants = [
    {
        name: 'ООО Фирма 1',
        productionTime: '80',
        warranty: '24',
        paymentTerms: '30',
        cost: 11000007,
        costDiscount: 25000,
        costTotal: 11000007 - 25000,
        qualityStandards: '-',
        actions: '-',
        id: '1',
        active: false,
        participantNumber: '1',
    },
    {
        name: 'ООО Фирма 2',
        productionTime: '80',
        warranty: '24',
        paymentTerms: '30',
        cost: 10005050,
        costDiscount: 25000,
        costTotal: 10005050 - 25000,
        qualityStandards: '-',
        actions: '-',
        id: '2',
        active: true,
        participantNumber: '2',
    },
    {
        name: 'ООО Фирма 3',
        productionTime: '80',
        warranty: '24',
        paymentTerms: '30',
        cost: 12000000,
        costDiscount: 25000,
        costTotal: 12000000 - 25000,
        qualityStandards: '-',
        actions: '-',
        id: '3',
        active: false,
        participantNumber: '3',
    },
]

export default ListOfParticipants;